version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - SCRAPER_URL=http://python-scraper:8000
      - DB_HOST=mariadb
      - DB_PORT=3306
    depends_on:
      - python-scraper
      - mariadb
  python-scraper:
    build: ./python-scraper
    ports:
      - '8000:8000'
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
  mariadb:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ride_fares
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: